### PR TITLE
Add "is connecting from xxx.xxx.xxx.xxx" to the FAQ

### PR DESCRIPTION
**Pull request by mission712**
Since a lot of users ask why this happens, I propose we add this to the FAQ.

### CODE REVIEW

**Comment by Mikaela** [comment]
I think the "xxx.xxx.xxx.xxx" should be replaced with "\<my IP address\>" or something as it seems to match only legacy IP addresses.

**Comment by mission712** [comment]
Acceptable. Changing that.

**Comment by mistohise** [comment]
I don't like the final part where it says "keep in mind that, without a cloak, your IP is still visible". 
I think it's unnecessary in the context of explaining what the "is connecting from:" line means, and introduces confusion around the effectiveness of cloaks hiding IPs.

**Comment by Mikaela** [comment]
https://gist.github.com/maxteufel/1e2cf7ada079c271bd3c

**Comment by mistohise** [comment]
We can't use that because it carries a copyright notice and is overly wordy in any event.  My point was more to exclude the references to what the cloak may or may not achieve.

**Comment by mission712** [comment]
mistohise: Acceptable. Removing it.

**Pull request merged**
