### PR TITLE
Clean up old files.

### PR DESCRIPTION
**Pull request by RhysBower**
Deleted old unused files and moved the styles.css into the static directory.

### CODE REVIEW

**Comment by RhysBower** [comment]
My new commits have been added to this pull request however only the first two commits "Remove unused images." and "Move styles.css to static directory." should be considered in this request.

**Comment by TingPing** [comment]
@RhysBower To fix that:

```sh
git checkout -b my-other-stuff
git checkout master
git reset --hard abeeb36
git push -f origin master
```

**Comment by RhysBower** [comment]
Thanks @TingPing I have fixed my branch.

**Comment by kjayne** [comment]
The whole static directory comes from an old framework that's not used since we killed the in-page-tabbed version of the FAQ and group registration. If anything, it needs to be removed entirely, not have more things put into.

The unused images are left in place deliberately.

**Pull request closed without merging**
